var txCoords = '''[
  {
    "code": "ABI",
    "lat": "32.4164",
    "lon": "-99.6803",
    "name": "Abilene Regional Airport",
    "city": "Abilene",
    "state": "Texas",
    "country": "United States",
    "woeid": "12518518",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "7199",
    "elev": "1790",
    "icao": "KABI",
    "direct_flights": "2",
    "carriers": "4"
  },
  {
    "code": "ACT",
    "lat": "31.609",
    "lon": "-97.2234",
    "name": "Waco Regional Airport",
    "city": "Waco",
    "state": "Texas",
    "country": "United States",
    "woeid": "12522299",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "6597",
    "elev": "516",
    "icao": "KACT",
    "direct_flights": "2",
    "carriers": "2"
  },
  {
    "code": "AMA",
    "lat": "35.2177",
    "lon": "-101.706",
    "name": "Amarillo International Airport",
    "city": "Amarillo",
    "state": "Texas",
    "country": "United States",
    "woeid": "12518598",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "13502",
    "elev": "3606",
    "icao": "KAMA",
    "direct_flights": "7",
    "carriers": "10"
  },
  {
    "code": "AUS",
    "lat": "30.2027",
    "lon": "-97.6653",
    "name": "Austin-Bergstrom International Airport",
    "city": "Austin",
    "state": "Texas",
    "country": "United States",
    "woeid": "23418445",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "http://www.abia.org/",
    "runway_length": "12248",
    "elev": "542",
    "icao": "KAUS",
    "direct_flights": "50",
    "carriers": "37"
  },
  {
    "code": "BPT",
    "lat": "29.9551",
    "lon": "-94.0185",
    "name": "Jefferson County Airport",
    "city": "Beaumont",
    "state": "Texas",
    "country": "United States",
    "woeid": "12520357",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "6751",
    "elev": "16",
    "icao": "KBPT",
    "direct_flights": "1",
    "carriers": "4"
  },
  {
    "code": "BRO",
    "lat": "25.9064",
    "lon": "-97.4321",
    "name": "Brownsville-South Padre Island International Air",
    "city": "Brownsville",
    "state": "Texas",
    "country": "United States",
    "woeid": "12518951",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "7400",
    "elev": "22",
    "icao": "KBRO",
    "direct_flights": "5",
    "carriers": "9"
  },
  {
    "code": "CLL",
    "lat": "30.5938",
    "lon": "-96.3685",
    "name": "Easterwood Field Airport",
    "city": "College Station",
    "state": "Texas",
    "country": "United States",
    "woeid": "12519579",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "7000",
    "elev": "319",
    "icao": "KCLL",
    "direct_flights": "2",
    "carriers": "4"
  },
  {
    "code": "CRP",
    "lat": "27.7747",
    "lon": "-97.5019",
    "name": "Corpus Christi International Airport",
    "city": "Corpus Christi",
    "state": "Texas",
    "country": "United States",
    "woeid": "12519324",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "7508",
    "elev": "44",
    "icao": "KCRP",
    "direct_flights": "5",
    "carriers": "12"
  },
  {
    "code": "DAL",
    "lat": "32.8439",
    "lon": "-96.8496",
    "name": "Dallas Love Field Airport",
    "city": "Dallas",
    "state": "Texas",
    "country": "United States",
    "woeid": "12519401",
    "tz": "America/Chicago",
    "phone": "1-214-670-6073",
    "type": "Airports",
    "email": "",
    "url": "http://www.dallas-lovefield.com/",
    "runway_length": "8800",
    "elev": "487",
    "icao": "KDAL",
    "direct_flights": "19",
    "carriers": "8"
  },
  {
    "code": "DFW",
    "lat": "32.9222",
    "lon": "-97.0409",
    "name": "Fort Worth International Airport",
    "city": "Dallas",
    "state": "Texas",
    "country": "United States",
    "woeid": "12519786",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "11388",
    "elev": "603",
    "icao": "KDFW",
    "direct_flights": "179",
    "carriers": "62"
  },
  {
    "code": "DRT",
    "lat": "29.3702",
    "lon": "-100.918",
    "name": "Del Rio International Airport",
    "city": "Del Rio",
    "state": "Texas",
    "country": "United States",
    "woeid": "12519452",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "5105",
    "elev": "999",
    "icao": "KDRT",
    "direct_flights": "1",
    "carriers": "1"
  },
  {
    "code": "ELP",
    "lat": "31.7982",
    "lon": "-106.393",
    "name": "El Paso International Airport",
    "city": "El Paso",
    "state": "Texas",
    "country": "United States",
    "woeid": "12519608",
    "tz": "America/Denver",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "11012",
    "elev": "3956",
    "icao": "KELP",
    "direct_flights": "20",
    "carriers": "23"
  },
  {
    "code": "GGG",
    "lat": "32.3874",
    "lon": "-94.7194",
    "name": "Gregg County Airport",
    "city": "Longview",
    "state": "Texas",
    "country": "United States",
    "woeid": "12520015",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "10000",
    "elev": "365",
    "icao": "KGGG",
    "direct_flights": "1",
    "carriers": "1"
  },
  {
    "code": "GRK",
    "lat": "31.0615",
    "lon": "-97.8206",
    "name": "Killeen-Fort Hood Regional Airport",
    "city": "Killeen",
    "state": "Texas",
    "country": "United States",
    "woeid": "12521608",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Military Airport",
    "email": "",
    "url": "",
    "runway_length": null,
    "elev": null,
    "icao": "KGRK",
    "direct_flights": "3",
    "carriers": "4"
  },
  {
    "code": "HOU",
    "lat": "29.6572",
    "lon": "-95.2795",
    "name": "William P Hobby Airport",
    "city": "Houston",
    "state": "Texas",
    "country": "United States",
    "woeid": "12522451",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "7602",
    "elev": "47",
    "icao": "KHOU",
    "direct_flights": "33",
    "carriers": "12"
  },
  {
    "code": "HRL",
    "lat": "26.2216",
    "lon": "-97.663",
    "name": "Grande Valley International Airport",
    "city": "Harlingen",
    "state": "Texas",
    "country": "United States",
    "woeid": "12519957",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "8300",
    "elev": "36",
    "icao": "KHRL",
    "direct_flights": "9",
    "carriers": "10"
  },
  {
    "code": "IAH",
    "lat": "29.9784",
    "lon": "-95.3424",
    "name": "George Bush Intercontinental Airport",
    "city": "Houston",
    "state": "Texas",
    "country": "United States",
    "woeid": "12520245",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "12001",
    "elev": "98",
    "icao": "KIAH",
    "direct_flights": "210",
    "carriers": "54"
  },
  {
    "code": "LBB",
    "lat": "33.6566",
    "lon": "-101.821",
    "name": "Lubbock International Airport",
    "city": "Lubbock",
    "state": "Texas",
    "country": "United States",
    "woeid": "12520718",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "http://www.flylia.com/",
    "runway_length": "11500",
    "elev": "3281",
    "icao": "KLBB",
    "direct_flights": "10",
    "carriers": "11"
  },
  {
    "code": "LRD",
    "lat": "27.5431",
    "lon": "-99.4555",
    "name": "Laredo International Airport",
    "city": "Laredo",
    "state": "Texas",
    "country": "United States",
    "woeid": "12520571",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "8201",
    "elev": "508",
    "icao": "KLRD",
    "direct_flights": "13",
    "carriers": "15"
  },
  {
    "code": "MAF",
    "lat": "31.9361",
    "lon": "-102.208",
    "name": "Midland International Airport",
    "city": "Midland",
    "state": "Texas",
    "country": "United States",
    "woeid": "12520944",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "9501",
    "elev": "2871",
    "icao": "KMAF",
    "direct_flights": "8",
    "carriers": "11"
  },
  {
    "code": "MFE",
    "lat": "26.1813",
    "lon": "-98.2404",
    "name": "Miller International Airport",
    "city": "Mcallen",
    "state": "Texas",
    "country": "United States",
    "woeid": "12520953",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "7108",
    "elev": "107",
    "icao": "KMFE",
    "direct_flights": "4",
    "carriers": "11"
  },
  {
    "code": "SAT",
    "lat": "29.5252",
    "lon": "-98.4729",
    "name": "San Antonio International Airport",
    "city": "San Antonio",
    "state": "Texas",
    "country": "United States",
    "woeid": "12521716",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "8502",
    "elev": "809",
    "icao": "KSAT",
    "direct_flights": "44",
    "carriers": "34"
  },
  {
    "code": "SJT",
    "lat": "31.3616",
    "lon": "-100.507",
    "name": "Mathis Field Airport",
    "city": "San Angelo",
    "state": "Texas",
    "country": "United States",
    "woeid": "12520840",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "6920",
    "elev": "1916",
    "icao": "KSJT",
    "direct_flights": "3",
    "carriers": "4"
  },
  {
    "code": "SPS",
    "lat": "33.9862",
    "lon": "-98.4984",
    "name": "Sheppard Air Force Base",
    "city": "Wichita Falls",
    "state": "Texas",
    "country": "United States",
    "woeid": "12521831",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Military Airport",
    "email": "",
    "url": "",
    "runway_length": "13100",
    "elev": "1015",
    "icao": "KSPS",
    "direct_flights": "2",
    "carriers": "3"
  },
  {
    "code": "TYR",
    "lat": "32.3506",
    "lon": "-95.4118",
    "name": "Tyler Pounds Field Airport",
    "city": "Tyler",
    "state": "Texas",
    "country": "United States",
    "woeid": "12522238",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "7200",
    "elev": "544",
    "icao": "KTYR",
    "direct_flights": "2",
    "carriers": "3"
  },
  {
    "code": "VCT",
    "lat": "28.8449",
    "lon": "-96.9201",
    "name": "Victoria Regional Airport",
    "city": "Victoria",
    "state": "Texas",
    "country": "United States",
    "woeid": "12522283",
    "tz": "America/Chicago",
    "phone": "",
    "type": "Airports",
    "email": "",
    "url": "",
    "runway_length": "9102",
    "elev": "115",
    "icao": "KVCT",
    "direct_flights": "1",
    "carriers": "1"
  },
]''';
